;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attribute.Damage.Elemental",DevComment="")
+GameplayTagList=(Tag="Attribute.Damage.Physical",DevComment="")
+GameplayTagList=(Tag="Attribute.Defense.Elemental",DevComment="")
+GameplayTagList=(Tag="Attribute.Defense.Physical",DevComment="")
+GameplayTagList=(Tag="Attribute.Health",DevComment="")
+GameplayTagList=(Tag="Attribute.Level",DevComment="")
+GameplayTagList=(Tag="Attribute.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Attribute.MinHealth",DevComment="")

+GameplayTagList=(Tag="Data.Attribute.ElementalDamage",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.ElementalDefense",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.Health",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.Level",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.Mana",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.MinHealth",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.PhysicalDamage",DevComment="")
+GameplayTagList=(Tag="Data.Attribute.PhysicalDefense",DevComment="")

+GameplayTagList=(Tag="Equipment.Category.Skill",DevComment="")
+GameplayTagList=(Tag="Equipment.Category.Weapon",DevComment="")
+GameplayTagList=(Tag="Equipment.Cooldown",DevComment="")
+GameplayTagList=(Tag="Equipment.Event.Attach",DevComment="")
+GameplayTagList=(Tag="Equipment.Event.Detach",DevComment="")

+GameplayTagList=(Tag="Event.Combat.Attack",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Swap",DevComment="")