// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

// Engine Headers
#include "CoreMinimal.h"
#include "NativeGameplayTags.h"



// Gameplay Tags
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_Walk);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_Fall);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_Fly);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_Swim);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Jump);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Sprint);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Ground_Idle);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Ground_Sprint);

// Deprecated
// RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Consume);
// RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Recover);
// ~ Deprecated


RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Ability);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Draining);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Regenerating);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Drain_Start);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Drain_Started);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Drain_Stop);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Drain_Stopped);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Regenerate_Start);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Regenerate_Stop);