// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

// Engine Headers
#include "CoreMinimal.h"
#include "NativeGameplayTags.h"



// Gameplay Tags

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Jump);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Sprint);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Temporary_Damage);
// Deprecated
// RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Consume);
// RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Recover);
// ~ Deprecated


RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Ability);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Draining);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Regenerating);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Drain_Start);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Drain_Started);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Drain_Stop);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Drain_Stopped);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Regenerate_Start);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stamina_Regenerate_Stop);





RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_NavWalking);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_Walking);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_Falling);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_Flying);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_Swimming);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_None);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Mode_Custom);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Ground_Idling);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Ground_Sprinting);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Air_Gliding);

RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Movement_Jump);
RCORETAG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Movement_Sprint);


